# Generated by Django 6.0.2 on 2026-02-10 05:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR'), ('Rub', 'RUB')], default='UZS', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
