# Generated by Django 6.0.2 on 2026-02-10 05:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('wallet_type', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Bank kartasi')], default='naqd', max_length=10)),
                ('card_type', models.CharField(blank=True, choices=[('HUMO', 'Humo'), ('UZCARD', 'Uzcard'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Evro'), ('RUB', 'Rubl')], default='UZS', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamyon',
                'verbose_name_plural': 'Hamyonlar',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('wallet_type', 'naqd')), fields=('user', 'wallet_type', 'currency'), name='unique_naqd_wallet_per_currency'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('wallet_type', 'karta')), fields=('user', 'wallet_type', 'card_type', 'title', 'currency'), name='unique_card_wallet')],
            },
        ),
    ]
