# Generated by Django 6.0.2 on 2026-02-10 05:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Miqdor')),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Olinadigan miqdor')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Kurs')),
            ],
            options={
                'verbose_name': "O'tkazma",
                'verbose_name_plural': "O'tkazmalar",
                'ordering': ['-created_at'],
            },
        ),
    ]
