# Generated by Django 6.0.2 on 2026-02-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='wallets.wallet', verbose_name='Qaysi hamyondan'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='wallets.wallet', verbose_name='Qaysi hamyonga'),
        ),
    ]
